# 1. Laptop screen. 60hz for battery, 240hz when plugged
#monitor = eDP-2, 2560x1600@240, 5120x0, auto
#monitor = eDP-2, 2560x1600@60, 5120x0, auto
monitor = eDP-2, disable

# LG UltraFine
monitor = desc:LG Electronics LG ULTRAFINE 308NTYT8W962, 3840x2160@60, 0x0, 1.5

# Acer X32 V2
monitor = desc:Acer Technologies X32 V2 15380001D3900, 3840x2160@165, 2560x0, 1.5

misc {
    vrr = 1
    disable_hyprland_logo = true
    disable_splash_rendering = true
    disable_autoreload = true
}

binds {
    allow_workspace_cycles = false
}
